import type { SmartSpaceRule, SmartSpaceRules } from './manager';

export interface FieldDefinition {
  id: string;
  label: string;
  type: 'string' | 'number' | 'boolean' | 'date' | 'array' | 'enum';
  operators: string[];
  options?: Array<{ value: any; label: string }>;
  description?: string;
}

export interface OperatorDefinition {
  id: string;
  label: string;
  description: string;
  supportedTypes: string[];
}

export class RuleBuilder {
  // Available fields for building rules
  static getAvailableFields(): FieldDefinition[] {
    return [
      {
        id: 'type',
        label: 'Content Type',
        type: 'enum',
        operators: ['equals', 'not_equals'],
        options: [
          { value: 'note', label: 'Note' },
          { value: 'image', label: 'Image' },
          { value: 'article', label: 'Article' },
          { value: 'video', label: 'Video' },
          { value: 'pdf', label: 'PDF' },
          { value: 'quote', label: 'Quote' },
          { value: 'recipe', label: 'Recipe' },
          { value: 'tweet', label: 'Tweet' },
          { value: 'product', label: 'Product' },
          { value: 'link', label: 'Link' },
          { value: 'audio', label: 'Audio' }
        ],
        description: 'The type of content'
      },
      {
        id: 'title',
        label: 'Title',
        type: 'string',
        operators: ['contains', 'not_contains', 'equals', 'not_equals'],
        description: 'The title of the card'
      },
      {
        id: 'content',
        label: 'Content',
        type: 'string',
        operators: ['contains', 'not_contains'],
        description: 'The main content text'
      },
      {
        id: 'ai_tags',
        label: 'AI Tags',
        type: 'array',
        operators: ['contains', 'not_contains'],
        description: 'Tags automatically generated by AI'
      },
      {
        id: 'manual_tags',
        label: 'Manual Tags',
        type: 'array',
        operators: ['contains', 'not_contains'],
        description: 'Tags manually added by the user'
      },
      {
        id: 'ai_category',
        label: 'AI Category',
        type: 'enum',
        operators: ['equals', 'not_equals'],
        options: [
          { value: 'Work & Productivity', label: 'Work & Productivity' },
          { value: 'Learning & Education', label: 'Learning & Education' },
          { value: 'Health & Wellness', label: 'Health & Wellness' },
          { value: 'Technology', label: 'Technology' },
          { value: 'Creative & Design', label: 'Creative & Design' },
          { value: 'Personal', label: 'Personal' },
          { value: 'Reference', label: 'Reference' },
          { value: 'Entertainment', label: 'Entertainment' },
          { value: 'News & Current Events', label: 'News & Current Events' },
          { value: 'Finance', label: 'Finance' },
          { value: 'Travel', label: 'Travel' },
          { value: 'Food & Recipes', label: 'Food & Recipes' },
          { value: 'Other', label: 'Other' }
        ],
        description: 'Category assigned by AI analysis'
      },
      {
        id: 'source_domain',
        label: 'Source Domain',
        type: 'string',
        operators: ['equals', 'not_equals', 'contains', 'not_contains'],
        description: 'The domain where the content originated'
      },
      {
        id: 'is_pinned',
        label: 'Is Pinned',
        type: 'boolean',
        operators: ['equals'],
        options: [
          { value: true, label: 'Yes' },
          { value: false, label: 'No' }
        ],
        description: 'Whether the card is pinned'
      },
      {
        id: 'is_archived',
        label: 'Is Archived',
        type: 'boolean',
        operators: ['equals'],
        options: [
          { value: true, label: 'Yes' },
          { value: false, label: 'No' }
        ],
        description: 'Whether the card is archived'
      },
      {
        id: 'created_at',
        label: 'Created Date',
        type: 'date',
        operators: ['greater_than', 'less_than', 'equals'],
        description: 'When the card was created'
      }
    ];
  }

  // Available operators
  static getOperators(): OperatorDefinition[] {
    return [
      {
        id: 'equals',
        label: 'equals',
        description: 'Exactly matches the value',
        supportedTypes: ['string', 'number', 'boolean', 'date', 'enum']
      },
      {
        id: 'not_equals',
        label: 'does not equal',
        description: 'Does not match the value',
        supportedTypes: ['string', 'number', 'boolean', 'date', 'enum']
      },
      {
        id: 'contains',
        label: 'contains',
        description: 'Contains the text or includes the array item',
        supportedTypes: ['string', 'array']
      },
      {
        id: 'not_contains',
        label: 'does not contain',
        description: 'Does not contain the text or array item',
        supportedTypes: ['string', 'array']
      },
      {
        id: 'greater_than',
        label: 'is after',
        description: 'Is greater than or after the value',
        supportedTypes: ['number', 'date']
      },
      {
        id: 'less_than',
        label: 'is before',
        description: 'Is less than or before the value',
        supportedTypes: ['number', 'date']
      }
    ];
  }

  // Get operators for a specific field type
  static getOperatorsForField(fieldId: string): OperatorDefinition[] {
    const field = this.getAvailableFields().find(f => f.id === fieldId);
    if (!field) return [];

    const allOperators = this.getOperators();
    return allOperators.filter(op =>
      field.operators.includes(op.id) &&
      op.supportedTypes.includes(field.type)
    );
  }

  // Validate a rule
  static validateRule(rule: SmartSpaceRule): { valid: boolean; errors: string[] } {
    const errors: string[] = [];
    const field = this.getAvailableFields().find(f => f.id === rule.field);

    if (!field) {
      errors.push(`Unknown field: ${rule.field}`);
      return { valid: false, errors };
    }

    if (!field.operators.includes(rule.operator)) {
      errors.push(`Invalid operator "${rule.operator}" for field "${field.label}"`);
    }

    // Validate value based on field type
    switch (field.type) {
      case 'boolean':
        if (typeof rule.value !== 'boolean') {
          errors.push(`Field "${field.label}" requires a boolean value`);
        }
        break;

      case 'number':
        if (typeof rule.value !== 'number') {
          errors.push(`Field "${field.label}" requires a number value`);
        }
        break;

      case 'date':
        if (!(rule.value instanceof Date) && typeof rule.value !== 'string') {
          errors.push(`Field "${field.label}" requires a date value`);
        }
        break;

      case 'enum':
        if (field.options && !field.options.some(opt => opt.value === rule.value)) {
          errors.push(`Invalid value for field "${field.label}"`);
        }
        break;

      case 'string':
        if (typeof rule.value !== 'string') {
          errors.push(`Field "${field.label}" requires a string value`);
        }
        break;

      case 'array':
        if (rule.operator === 'contains' || rule.operator === 'not_contains') {
          if (typeof rule.value !== 'string') {
            errors.push(`Array operations require a string value to search for`);
          }
        }
        break;
    }

    return {
      valid: errors.length === 0,
      errors
    };
  }

  // Validate complete rules
  static validateRules(rules: SmartSpaceRules): { valid: boolean; errors: string[] } {
    const errors: string[] = [];

    if (!rules.conditions || rules.conditions.length === 0) {
      errors.push('At least one condition is required');
    }

    if (!['AND', 'OR'].includes(rules.logic)) {
      errors.push('Logic must be either "AND" or "OR"');
    }

    // Validate each condition
    rules.conditions?.forEach((condition, index) => {
      const validation = this.validateRule(condition);
      if (!validation.valid) {
        validation.errors.forEach(error => {
          errors.push(`Condition ${index + 1}: ${error}`);
        });
      }
    });

    return {
      valid: errors.length === 0,
      errors
    };
  }

  // Convert rules to human-readable description
  static rulesToDescription(rules: SmartSpaceRules): string {
    if (!rules.conditions || rules.conditions.length === 0) {
      return 'No conditions defined';
    }

    const conditions = rules.conditions.map(condition => {
      const field = this.getAvailableFields().find(f => f.id === condition.field);
      const operator = this.getOperators().find(op => op.id === condition.operator);

      if (!field || !operator) {
        return `Invalid condition: ${condition.field} ${condition.operator} ${condition.value}`;
      }

      let valueDisplay = condition.value;

      // Format value based on type
      if (field.type === 'enum' && field.options) {
        const option = field.options.find(opt => opt.value === condition.value);
        valueDisplay = option ? option.label : condition.value;
      } else if (field.type === 'date') {
        valueDisplay = new Date(condition.value).toLocaleDateString();
      } else if (field.type === 'boolean') {
        valueDisplay = condition.value ? 'Yes' : 'No';
      }

      return `${field.label} ${operator.label} "${valueDisplay}"`;
    });

    const logicWord = rules.logic === 'AND' ? 'and' : 'or';

    if (conditions.length === 1) {
      return conditions[0];
    } else if (conditions.length === 2) {
      return `${conditions[0]} ${logicWord} ${conditions[1]}`;
    } else {
      const lastCondition = conditions.pop();
      return `${conditions.join(', ')} ${logicWord} ${lastCondition}`;
    }
  }

  // Generate sample rules for common use cases
  static getSampleRules(): Array<{ name: string; description: string; rules: SmartSpaceRules }> {
    return [
      {
        name: 'Work Articles',
        description: 'Articles about work and productivity',
        rules: {
          conditions: [
            { field: 'type', operator: 'equals', value: 'article' },
            { field: 'ai_category', operator: 'equals', value: 'Work & Productivity' }
          ],
          logic: 'AND'
        }
      },
      {
        name: 'Recent Images',
        description: 'Images added in the last 30 days',
        rules: {
          conditions: [
            { field: 'type', operator: 'equals', value: 'image' },
            { field: 'created_at', operator: 'greater_than', value: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString() }
          ],
          logic: 'AND'
        }
      },
      {
        name: 'Tech Content',
        description: 'Any content tagged with technology or programming',
        rules: {
          conditions: [
            { field: 'ai_tags', operator: 'contains', value: 'technology' },
            { field: 'ai_tags', operator: 'contains', value: 'programming' },
            { field: 'ai_category', operator: 'equals', value: 'Technology' }
          ],
          logic: 'OR'
        }
      },
      {
        name: 'Important Notes',
        description: 'Pinned notes that are not archived',
        rules: {
          conditions: [
            { field: 'type', operator: 'equals', value: 'note' },
            { field: 'is_pinned', operator: 'equals', value: true },
            { field: 'is_archived', operator: 'equals', value: false }
          ],
          logic: 'AND'
        }
      },
      {
        name: 'Social Media',
        description: 'Content from Twitter or social platforms',
        rules: {
          conditions: [
            { field: 'type', operator: 'equals', value: 'tweet' },
            { field: 'source_domain', operator: 'contains', value: 'twitter' },
            { field: 'source_domain', operator: 'contains', value: 'x.com' }
          ],
          logic: 'OR'
        }
      },
      {
        name: 'Learning Resources',
        description: 'Educational content and learning materials',
        rules: {
          conditions: [
            { field: 'ai_category', operator: 'equals', value: 'Learning & Education' },
            { field: 'ai_tags', operator: 'contains', value: 'tutorial' },
            { field: 'ai_tags', operator: 'contains', value: 'course' }
          ],
          logic: 'OR'
        }
      }
    ];
  }

  // Create a rule from natural language (simple implementation)
  static createRuleFromDescription(description: string): SmartSpaceRule | null {
    const normalized = description.toLowerCase().trim();

    // Simple patterns - in a real implementation, this would be more sophisticated
    const patterns = [
      {
        pattern: /^type\s+(is|equals?)\s+(.+)$/,
        factory: (matches: string[]) => ({
          field: 'type',
          operator: 'equals' as const,
          value: matches[2].replace(/["']/g, '')
        })
      },
      {
        pattern: /^(title|content)\s+contains?\s+["'](.+)["']$/,
        factory: (matches: string[]) => ({
          field: matches[1] as any,
          operator: 'contains' as const,
          value: matches[2]
        })
      },
      {
        pattern: /^is\s+pinned$/,
        factory: () => ({
          field: 'is_pinned',
          operator: 'equals' as const,
          value: true
        })
      },
      {
        pattern: /^is\s+archived$/,
        factory: () => ({
          field: 'is_archived',
          operator: 'equals' as const,
          value: true
        })
      }
    ];

    for (const { pattern, factory } of patterns) {
      const match = normalized.match(pattern);
      if (match) {
        try {
          return factory(match);
        } catch (error) {
          console.error('Failed to create rule from pattern:', error);
        }
      }
    }

    return null;
  }

  // Export rules to JSON
  static exportRules(rules: SmartSpaceRules): string {
    return JSON.stringify(rules, null, 2);
  }

  // Import rules from JSON
  static importRules(json: string): { success: boolean; rules?: SmartSpaceRules; error?: string } {
    try {
      const rules = JSON.parse(json) as SmartSpaceRules;
      const validation = this.validateRules(rules);

      if (!validation.valid) {
        return {
          success: false,
          error: `Invalid rules: ${validation.errors.join(', ')}`
        };
      }

      return {
        success: true,
        rules
      };
    } catch (error) {
      return {
        success: false,
        error: `Invalid JSON: ${error instanceof Error ? error.message : 'Unknown error'}`
      };
    }
  }
}