#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Run lint-staged
npx lint-staged

# Run type checking
npm run type-check

# Run tests on changed files
npm run test -- --bail --findRelatedTests --passWithNoTests